// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'address.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Address _$AddressFromJson(Map<String, dynamic> json) => Address(
      id: json['Id'] as String?,
      domesticId: json['DomesticId'] as String?,
      language: json['Language'] as String?,
      languageAlternatives: json['LanguageAlternatives'] as String?,
      department: json['Department'] as String?,
      company: json['Company'] as String?,
      subBuilding: json['SubBuilding'] as String?,
      buildingNumber: json['BuildingNumber'] as String?,
      buildingName: json['BuildingName'] as String?,
      secondaryStreet: json['SecondaryStreet'] as String?,
      street: json['Street'] as String?,
      block: json['Block'] as String?,
      neighbourhood: json['Neighbourhood'] as String?,
      district: json['District'] as String?,
      city: json['City'] as String?,
      line1: json['Line1'] as String?,
      line2: json['Line2'] as String?,
      line3: json['Line3'] as String?,
      line4: json['Line4'] as String?,
      line5: json['Line5'] as String?,
      adminAreaName: json['AdminAreaName'] as String?,
      adminAreaCode: json['AdminAreaCode'] as String?,
      province: json['Province'] as String?,
      provinceName: json['ProvinceName'] as String?,
      provinceCode: json['ProvinceCode'] as String?,
      postalCode: json['PostalCode'] as String?,
      countryName: json['CountryName'] as String?,
      countryIso2: json['CountryIso2'] as String?,
      countryIso3: json['CountryIso3'] as String?,
      countryIsoNumber: json['CountryIsoNumber'] as String?,
      sortingNumber1: json['SortingNumber1'] as String?,
      sortingNumber2: json['SortingNumber2'] as String?,
      barcode: json['Barcode'] as String?,
      poBoxNumber: json['PoBoxNumber'] as String?,
      label: json['Label'] as String?,
      type: json['Type'] as String?,
      dataLevel: json['DataLevel'] as String?,
      field1: json['Field1'] as String?,
      field2: json['Field2'] as String?,
      field3: json['Field3'] as String?,
      field4: json['Field4'] as String?,
      field5: json['Field5'] as String?,
      field6: json['Field6'] as String?,
      field7: json['Field7'] as String?,
      field8: json['Field8'] as String?,
      field9: json['Field9'] as String?,
      field10: json['Field10'] as String?,
      field11: json['Field11'] as String?,
      field12: json['Field12'] as String?,
      field13: json['Field13'] as String?,
      field14: json['Field14'] as String?,
      field15: json['Field15'] as String?,
      field16: json['Field16'] as String?,
      field17: json['Field17'] as String?,
      field18: json['Field18'] as String?,
      field19: json['Field19'] as String?,
      field20: json['Field20'] as String?,
    );

Map<String, dynamic> _$AddressToJson(Address instance) => <String, dynamic>{
      'Id': instance.id,
      'DomesticId': instance.domesticId,
      'Language': instance.language,
      'LanguageAlternatives': instance.languageAlternatives,
      'Department': instance.department,
      'Company': instance.company,
      'SubBuilding': instance.subBuilding,
      'BuildingNumber': instance.buildingNumber,
      'BuildingName': instance.buildingName,
      'SecondaryStreet': instance.secondaryStreet,
      'Street': instance.street,
      'Block': instance.block,
      'Neighbourhood': instance.neighbourhood,
      'District': instance.district,
      'City': instance.city,
      'Line1': instance.line1,
      'Line2': instance.line2,
      'Line3': instance.line3,
      'Line4': instance.line4,
      'Line5': instance.line5,
      'AdminAreaName': instance.adminAreaName,
      'AdminAreaCode': instance.adminAreaCode,
      'Province': instance.province,
      'ProvinceName': instance.provinceName,
      'ProvinceCode': instance.provinceCode,
      'PostalCode': instance.postalCode,
      'CountryName': instance.countryName,
      'CountryIso2': instance.countryIso2,
      'CountryIso3': instance.countryIso3,
      'CountryIsoNumber': instance.countryIsoNumber,
      'SortingNumber1': instance.sortingNumber1,
      'SortingNumber2': instance.sortingNumber2,
      'Barcode': instance.barcode,
      'PoBoxNumber': instance.poBoxNumber,
      'Label': instance.label,
      'Type': instance.type,
      'DataLevel': instance.dataLevel,
      'Field1': instance.field1,
      'Field2': instance.field2,
      'Field3': instance.field3,
      'Field4': instance.field4,
      'Field5': instance.field5,
      'Field6': instance.field6,
      'Field7': instance.field7,
      'Field8': instance.field8,
      'Field9': instance.field9,
      'Field10': instance.field10,
      'Field11': instance.field11,
      'Field12': instance.field12,
      'Field13': instance.field13,
      'Field14': instance.field14,
      'Field15': instance.field15,
      'Field16': instance.field16,
      'Field17': instance.field17,
      'Field18': instance.field18,
      'Field19': instance.field19,
      'Field20': instance.field20,
    };
