// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'address.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Address _$AddressFromJson(Map<String, dynamic> json) => Address(
      id: json['id'] as String?,
      domesticId: json['domesticId'] as String?,
      language: json['language'] as String?,
      languageAlternatives: json['languageAlternatives'] as String?,
      department: json['department'] as String?,
      company: json['company'] as String?,
      subBuilding: json['subBuilding'] as String?,
      buildingNumber: json['buildingNumber'] as String?,
      buildingName: json['buildingName'] as String?,
      secondaryStreet: json['secondaryStreet'] as String?,
      street: json['street'] as String?,
      block: json['block'] as String?,
      neighbourhood: json['neighbourhood'] as String?,
      district: json['district'] as String?,
      city: json['city'] as String?,
      line1: json['line1'] as String?,
      line2: json['line2'] as String?,
      line3: json['line3'] as String?,
      line4: json['line4'] as String?,
      line5: json['line5'] as String?,
      adminAreaName: json['adminAreaName'] as String?,
      adminAreaCode: json['adminAreaCode'] as String?,
      province: json['province'] as String?,
      provinceName: json['provinceName'] as String?,
      provinceCode: json['provinceCode'] as String?,
      postalCode: json['postalCode'] as String?,
      countryName: json['countryName'] as String?,
      countryIso2: json['countryIso2'] as String?,
      countryIso3: json['countryIso3'] as String?,
      countryIsoNumber: json['countryIsoNumber'] as String?,
      sortingNumber1: json['sortingNumber1'] as String?,
      sortingNumber2: json['sortingNumber2'] as String?,
      barcode: json['barcode'] as String?,
      poBoxNumber: json['poBoxNumber'] as String?,
      label: json['label'] as String?,
      type: json['type'] as String?,
      dataLevel: json['dataLevel'] as String?,
      field1: json['field1'] as String?,
      field2: json['field2'] as String?,
      field3: json['field3'] as String?,
      field4: json['field4'] as String?,
      field5: json['field5'] as String?,
      field6: json['field6'] as String?,
      field7: json['field7'] as String?,
      field8: json['field8'] as String?,
      field9: json['field9'] as String?,
      field10: json['field10'] as String?,
      field11: json['field11'] as String?,
      field12: json['field12'] as String?,
      field13: json['field13'] as String?,
      field14: json['field14'] as String?,
      field15: json['field15'] as String?,
      field16: json['field16'] as String?,
      field17: json['field17'] as String?,
      field18: json['field18'] as String?,
      field19: json['field19'] as String?,
      field20: json['field20'] as String?,
    );

Map<String, dynamic> _$AddressToJson(Address instance) => <String, dynamic>{
      'id': instance.id,
      'domesticId': instance.domesticId,
      'language': instance.language,
      'languageAlternatives': instance.languageAlternatives,
      'department': instance.department,
      'company': instance.company,
      'subBuilding': instance.subBuilding,
      'buildingNumber': instance.buildingNumber,
      'buildingName': instance.buildingName,
      'secondaryStreet': instance.secondaryStreet,
      'street': instance.street,
      'block': instance.block,
      'neighbourhood': instance.neighbourhood,
      'district': instance.district,
      'city': instance.city,
      'line1': instance.line1,
      'line2': instance.line2,
      'line3': instance.line3,
      'line4': instance.line4,
      'line5': instance.line5,
      'adminAreaName': instance.adminAreaName,
      'adminAreaCode': instance.adminAreaCode,
      'province': instance.province,
      'provinceName': instance.provinceName,
      'provinceCode': instance.provinceCode,
      'postalCode': instance.postalCode,
      'countryName': instance.countryName,
      'countryIso2': instance.countryIso2,
      'countryIso3': instance.countryIso3,
      'countryIsoNumber': instance.countryIsoNumber,
      'sortingNumber1': instance.sortingNumber1,
      'sortingNumber2': instance.sortingNumber2,
      'barcode': instance.barcode,
      'poBoxNumber': instance.poBoxNumber,
      'label': instance.label,
      'type': instance.type,
      'dataLevel': instance.dataLevel,
      'field1': instance.field1,
      'field2': instance.field2,
      'field3': instance.field3,
      'field4': instance.field4,
      'field5': instance.field5,
      'field6': instance.field6,
      'field7': instance.field7,
      'field8': instance.field8,
      'field9': instance.field9,
      'field10': instance.field10,
      'field11': instance.field11,
      'field12': instance.field12,
      'field13': instance.field13,
      'field14': instance.field14,
      'field15': instance.field15,
      'field16': instance.field16,
      'field17': instance.field17,
      'field18': instance.field18,
      'field19': instance.field19,
      'field20': instance.field20,
    };
